### ISSUE TITLE
microG Update

### ISSUE THREAD

**Issue by vanMacG** [lineageos4microg/android_vendor_partner_gms#1]
Hello,
just a quick reminder, microG was [updated](https://github.com/microg/GmsCore/releases/tag/v0.2.23.214816): https://microg.org/fdroid/repo/com.google.android.gms-214816046.apk
Can you please update the included apk.
Thanks!

**Comment by bananer** [comment]
done with https://github.com/lineageos4microg/android_vendor_partner_gms/commit/3b8b3820fbdb01f6ed28bfa1be5974470fef705b
