### ISSUE TITLE
android 12 with signal app

### ISSUE THREAD

**Issue by gustlik** [lineageos4microg/android_vendor_partner_gms#10]
Hi, do you plan to add microg patch mentioned in https://calyxos.org/news/2022/03/03/microg-android-12/ ?

thank you

**Comment by ale5000-git** [comment]
The fix is already merged but there isn't a new version og microG yet.
You can wait the new release or try the nightly build at https://microg.org/dl/core-nightly.apk

**Comment by ale5000-git** [comment]
The latest release now include the fix.
