### ISSUE TITLE
Changes for LOS 19 have broken LOS 18 builds

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/android_vendor_partner_gms#17]
Building 18.1 using the `master` branch of this repo fails with the following error
> 
> `FAILED: ninja: 'out/target/common/obj/JAVA_LIBRARIES/androidx.window.extensions_intermediates/javalib.jar', needed by 'out/target/product/avicii/obj/APPS/GmsCore_intermediates/dexpreopt.zip', missing and no known rule to make it ` I'm using the same prebuilts for both build attempts: ` <project name="lineageos4microg/android_vendor_partner_gms" path="vendor/partner_gms" remote="github" revision="master" />`

_Originally posted by @petefoth in https://github.com/lineageos4microg/android_vendor_partner_gms/issues/13#issuecomment-1354305829_

~~Two lines were~~ A line was added to `GmsCore/Android.mk` in [this commit](https://github.com/lineageos4microg/android_vendor_partner_gms/commit/881962077efaa799cb879df19639497558b13f75) ~~and [this commit](https://github.com/lineageos4microg/android_vendor_partner_gms/commit/f0fc4d689183860c0de19dd3461641a04a9b7cd7)~~ to fix the issue with building 19.1
```
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
```

If I remove ~~these two lines~~ this line, then my 18.1 builds succeed.

Is it possible make the inclusion of those lines conditional on the Lineage OS version or Android version?

**Comment by giovEra** [comment]
I preferred to create three separate branches, but if you prefer to continue using just one, then something like this should work:

```
ifeq ( ,$(filter android-32, $(TARGET_PLATFORM)))
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
endif
```

**Comment by giovEra** [comment]
I forgot los-19.0:

```diff
- ifeq ( ,$(filter android-32, $(TARGET_PLATFORM)))
+ ifeq ( ,$(filter android-31 android-32, $(TARGET_PLATFORM)))
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
endif
```
So the Android.mk should look like [this](https://pastebin.com/V2BNknAd).

**Comment by petefoth** [comment]
> So the Android.mk should look like [this](https://pastebin.com/V2BNknAd).

Thank you. I was hoping to find a way of doing
```
IF $(TARGET_PLATFORM) GREATER THAN 18 
    LOCAL_USES_LIBRARIES 
```

I was also wondering how the regular 18.1 builds at `https://download.lineage.microg.org` have been working since this change, but looking at   downloads for e.g. `z3`, the [latest available build](https://download.lineage.microg.org/z3/)  is dated 16/10/2022, but the [latest official Lineage buiild](https://download.lineageos.org/z3) is from yesterday. 

So it looks like [commit 8819620](https://github.com/lineageos4microg/android_vendor_partner_gms/commit/881962077efaa799cb879df19639497558b13f75] di break the builds here too.

I'll try and get a pull request done in the next day or so.

Thanks again





but it seems `make` only has `ifeq`, `ifneq`, and `ifdef` conditionals

**Comment by petefoth** [comment]
The makefile now looks like this, but the build is still failing
```
ifeq ( ,$(filter android-31 android-32, $(TARGET_PLATFORM)))
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
endif
```

The I tried making it conditional on only `android-31`, still no joy 
`ifeq ( ,$(filter android-31 android-32, $(TARGET_PLATFORM)))`

If I remove the `LOCAL_OPTIONAL_USES_LIBRARIES :` line then everything

So
1. The problem is  caused by [**this** commit](https://github.com/lineageos4microg/android_vendor_partner_gms/commit/881962077efaa799cb879df19639497558b13f75). The other commit is not a problem. (original post edited)
2. I can't find a way that works of making the line conditional. Until someone cleverer than me finds a way to do that I will work around the problem by patching the file to remove the problematic line. 

Thanks for your help, but I think I'm done here :(

**Comment by giovEra** [comment]
@petefoth I got confused in reading 😃 

You wanted to include the two lines if you compile los-19.0/1 and exclude them when you compile los-18.1.
The code I gave you does the opposite 🤣 

## Explanation:
```ifeq ( ,$(filter android-31 android-32, $(TARGET_PLATFORM)))```
Return the strings (android-31 or android-32), which match any element of $(TARGET_PLATFORM).
And compares the previous result with the empty string.
So the condition is "true" if there is no mach of either android-31 or android-32 in $(TARGET_PLATFORM).

## Therefore:

Choice 1: change from "if it is true then" to "if it is false then"
```diff
- ifeq ( ,$(filter android-31 android-32, $(TARGET_PLATFORM)))
+ ifneq ( ,$(filter android-31 android-32, $(TARGET_PLATFORM)))
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
endif
```
[Android.mk](https://pastebin.com/kpB6LLdB)

Choice 2: change the condition
```
extra_lines_for_los := android-31 android-32

ifeq ($(filter $(extra_lines_for_los),$(TARGET_PLATFORM)),$(TARGET_PLATFORM))
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
endif
```
[Android.mk](https://pastebin.com/A5mGsPf0)

**Comment by petefoth** [comment]
Thank you!

I will try out those changes. And while the build is in progress, I will try and work out what exactly they are doing :)

/me settles down with a copy of https://www.gnu.org/software/make/manual/html_node/Text-Functions.html

**Comment by petefoth** [comment]
> You wanted to include the two lines if you compile los-19.0/1 and exclude them when you compile los-18.1.
> The code I gave you does the opposite 🤣

I found a slightly different conditional [used by /e/ OS to fix this problem with their builds](https://gitlab.e.foundation/e/os/android_prebuilts_prebuiltapks_lfs/-/commit/f0079b1a3fd7d8e3775b56f94eac56c6e97823e7)
`ifneq ($(call math_gt_or_eq, $(PLATFORM_SDK_VERSION), 31),)`

I've tried that, and it works with 18.1 builds. Next step is to try it with 19.1 and 20.0 builds. If they all work, then I'll change the status of PR #18 so it can be merged

**Comment by petefoth** [comment]
18.1 and 19.1 builds were successful. 

I will do a 20.0 build eventually, but I cant see any reason it would fail, so I have changed the status of PR https://github.com/lineageos4microg/android_vendor_partner_gms/pull/18 so it can be merged

I will close the issue when the PR is merged.
