### ISSUE TITLE
UnifiedNlp not working on coral

### ISSUE THREAD

**Issue by LOSUser** [lineageos4microg/android_vendor_partner_gms#2]
Unfortunately UnifiedNlp is not working for me on coral (Pixel 4 XL). There is even no UnifiedNlp section in MicroG Self-Check — last position on that list is "Battery optimizations ignored" under "System". What can I provide you with to help diagnose this issue?

**Comment by bananer** [comment]
Sounds more like an issue with microG... There was a bugfix release recently, maybe that fixes it for you: https://github.com/microg/GmsCore/releases/tag/v0.2.24.214816

**Comment by vanMacG** [comment]
@bananer Could you please update the microg apk in this repo here as well. This also includes a hotfix for exposure notification. Thank you!

**Comment by bananer** [comment]
@vanMacG just updated with the new microG version

**Comment by LOSUser** [comment]
> Sounds more like an issue with microG... There was a bugfix release recently, maybe that fixes it for you: https://github.com/microg/GmsCore/releases/tag/v0.2.24.214816

Unfortunately this doesn't change anything for me — everything's still the same.

**Comment by bananer** [comment]
> There is even no UnifiedNlp section in MicroG Self-Check

I don't think there should be one. The "Location modules" section is in microG Settings main screen, between "Safetynet" and "Exposure notifications". Are you seeing that?

Generally, what makes you conclude that unifiedNlp is not working?

**Comment by LOSUser** [comment]
There should be, as evidenced by this screenshot (from [here](https://github.com/microg/UnifiedNlp/issues/158)):
![screenshot](https://user-images.githubusercontent.com/39718166/40635975-25bf5f06-6340-11e8-8a94-305f82a3c905.png)

**Comment by bananer** [comment]
That screenshot is rather old, seems like those checks were disabled since: https://github.com/microg/GmsCore/blame/ad12bd5de4970a6607a18e37707fab9f444593a7/play-services-core/src/main/java/org/microg/gms/ui/SelfCheckFragment.java#L102

**Comment by LOSUser** [comment]
Well spotted! It seems like the UnifiedNlp might have started working on my phone after all, but I'm still not sure about the accuracy of different backends. How could I see what each of the backends provides?

**Comment by bananer** [comment]
I don't think there is an issue with lineageos4microg here.

If you want more troubleshooting output for NLP, you could suggest this over at https://github.com/microg/UnifiedNlp

If you're not happy with network location in l4m, you could install additional providers like https://github.com/microg/AppleWifiNlpBackend and [Deja Vu](https://f-droid.org/de/packages/org.fitchfamily.android.dejavu/)
