### ISSUE TITLE
Update GmsCore version to v0.3.x

### ISSUE THREAD

**Issue by argonym** [lineageos4microg/android_vendor_partner_gms#25]
Currently included GmsCore is version 0.2.27.223616 (around one year old).

https://github.com/microg/GmsCore/releases

I'd like to use the new location stack (and plenty of bug fixes).
So updating GmsCore requires other changes (e.g. removing the location backend apks).

**Comment by argonym** [comment]
Ah, I see now why it's not updated yet.
v0.2.27 still is the stable version.
https://microg.org/download.html

**Comment by petefoth** [comment]
> v0.2.27 still is the stable version

Indeed.
 If you want to use 3.0, you can: in F-Droid | Settings | Installed apps | microG Services, enable "Allow Beta updates". and you should immediatey get 'updated' to v0.3
