### ISSUE TITLE
Mention signature spoofing patch in readme.md for users not building with docker

### ISSUE THREAD

**Issue by K4sum1** [lineageos4microg/android_vendor_partner_gms#27]
So I figured out my problem. I have never used docker, therefore I never read the docker readme. (My main system can't even run docker, I have been compiling in a Ubuntu VM in VMware with snapshots) It mentions needing a signature spoofing patch, something missing from the readme here.

At the bottom of this I found the mention of the patches and applied the one for Android Q.
https://github.com/microg/GmsCore/wiki/Signature-Spoofing
At first building failed because there were two .old files the compiler complained about, but deleting them allowed me to compile the build, and it isn't bootlooping or being weird in my limited testing so far. This is with the XZ1C too, will try to main it again and see if I encounter any weirdness.

Not sure if this is also required after applying the patch, but I ran export SIGNATURE_SPOOFING=restricted as well before compiling.

**Comment by petefoth** [comment]
Done!



> Not sure if this is also required after applying the patch, but I ran export SIGNATURE_SPOOFING=restricted as well before compiling.

You shouldn't need to do that: the variable only controls whether the Docker engine applies the patches: see [here](https://github.com/lineageos4microg/docker-lineage-cicd/blob/c77eabe036a1620499a8c087b732e039e0734656/src/build.sh#L220C1-L241C9)

**Comment by K4sum1** [comment]
> Done!
> 
> > Not sure if this is also required after applying the patch, but I ran export SIGNATURE_SPOOFING=restricted as well before compiling.
> 
> You shouldn't need to do that: the variable only controls whether the Docker engine applies the patches: see [here](https://github.com/lineageos4microg/docker-lineage-cicd/blob/c77eabe036a1620499a8c087b732e039e0734656/src/build.sh#L220C1-L241C9)

Ok, does the patch default to restricted or yes? I would prefer to have it restricted.

**Comment by petefoth** [comment]
> Ok, does the patch default to restricted or yes? I would prefer to have it restricted.

Look at [this block of code](https://github.com/lineageos4microg/docker-lineage-cicd/blob/c77eabe036a1620499a8c087b732e039e0734656/src/build.sh#L220C1-L250C1)

<details><summary>code</summary>

```

    # If needed, apply the microG's signature spoofing patch
    if [ "$SIGNATURE_SPOOFING" = "yes" ] || [ "$SIGNATURE_SPOOFING" = "restricted" ]; then
      # Determine which patch should be applied to the current Android source tree
      cd frameworks/base
      if [ "$SIGNATURE_SPOOFING" = "yes" ]; then
        echo ">> [$(date)] Applying the standard signature spoofing patch ($frameworks_base_patch) to frameworks/base"
        echo ">> [$(date)] WARNING: the standard signature spoofing patch introduces a security threat"
        patch --quiet --force -p1 -i "/root/signature_spoofing_patches/$frameworks_base_patch"
      else
        echo ">> [$(date)] Applying the restricted signature spoofing patch (based on $frameworks_base_patch) to frameworks/base"
        sed 's/android:protectionLevel="dangerous"/android:protectionLevel="signature|privileged"/' "/root/signature_spoofing_patches/$frameworks_base_patch" | patch --quiet --force -p1
      fi
      git clean -q -f
      cd ../..


      if [ -n "$apps_permissioncontroller_patch" ] && [ "$SIGNATURE_SPOOFING" = "yes" ]; then
        cd packages/apps/PermissionController
        echo ">> [$(date)] Applying the apps/PermissionController patch ($apps_permissioncontroller_patch) to packages/apps/PermissionController"
        patch --quiet --force -p1 -i "/root/signature_spoofing_patches/$apps_permissioncontroller_patch"
        git clean -q -f
        cd ../../..
      fi


      if [ -n "$modules_permission_patch" ] && [ "$SIGNATURE_SPOOFING" = "yes" ]; then
        cd packages/modules/Permission
        echo ">> [$(date)] Applying the modules/Permission patch ($modules_permission_patch) to packages/modules/Permission"
        patch --quiet --force -p1 -i "/root/signature_spoofing_patches/$modules_permission_patch"
        git clean -q -f
        cd ../../..
      fi


```

</details>

- For `restricted` spoofing you need to do whatever that code would do if `SIGNATURE_SPOOFING=restricted` 
- For full spoofing you need to do whatever that code would do if `SIGNATURE_SPOOFING=yes`
