### ISSUE TITLE
Original Play Store not recognized as "authentic"

### ISSUE THREAD

**Issue by powellnorma** [lineageos4microg/android_vendor_partner_gms#29]
Could it be the case, that due to the way the signature-spoofing works, when the "fake" `com.android.vending` (Fake Store) with the real one (plain Play Store), it is recognized as "unverified"?

See:
https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/68
https://github.com/nift4/microg_installer_revived/issues/141

**Comment by petefoth** [comment]
In the linked MinMicroG issue you say
> use "LineageOS for microG", and installed [MinMicroG-Standard-2.12.0-20230729205842.zip](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/tag/2023.07.29) via Magisk

So you're trying to run two different versions of MIcroG components (ours and MinMicroG's) alongside each other? If that's the case I'm not surprised things don;t work as they should. I think you need to choose between running our build ***or*** running upstream 'plain' LIneageOS and installing MinMicrog

**Comment by powellnorma** [comment]
The exact method/check that fails is: `GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable` (see https://github.com/RikkaW/YASNAC/issues/22#issuecomment-1082696557).
What I find interesting is that re-installing the (final) App via the (new, real) Play Store fixes this issue.

It's as if the installer notes in some metadata who (e.g. what signature) the "official" PlayService is. Perhaps when installing it via "adb install", GMS sets that signature.

Either way, I have found a workaround (reinstalling via Play Store) - so feel free to close this issue
