### ISSUE TITLE
New versions of microG components have 'broken' the build

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/android_vendor_partner_gms#36]
microG have updated the `stable` versions of the GmsCore and GmsCompanion components to version `0.3.6`. We picked up these changes automatically in [the commits made yesterday (Dec 25, 2024)](https://github.com/lineageos4microg/android_vendor_partner_gms/commits/master/).  The changes in these versions have 'broken' our builds, which are failing with the following errors:
```
[ 94% 181469/191934] Verifying uses-libraries: vendor/partner_gms/FakeStore/FakeStore.apk (priority: 12)
FAILED: out/target/product/renoir/obj/APPS/FakeStore_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/product/renoir/obj/APPS/FakeStore_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/product/renoir/obj/APPS/FakeStore_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt2 	   	   	   	   	  vendor/partner_gms/FakeStore/FakeStore.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (vendor/partner_gms/FakeStore/FakeStore.apk):
		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'androidx.window.sidecar'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- for details, see build/make/Changes.md and https://source.android.com/devices/tech/dalvik/art-class-loader-context
```
We need to make some changes in this repo before we can start building again.

The last device to build successfully was `redfin`. The following devices have not yet been built this month: `renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif,socrates,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,vela,voyager,wade,walleye,xpeng,xz2c,Z01R,zippo`

**Comment by petefoth** [comment]
It appears to be only FakeStore that is broken. Earlier changes caused exactly this issue in GmsCore. THese wer fixed by adding the [following lines in that component's `Android.mk`](https://github.com/lineageos4microg/android_vendor_partner_gms/blob/5738e0fb05ebef12f2bfbba3c799ad02d263b876/GmsCore/Android.mk#L34-L37)
```
ifneq ($(call math_gt_or_eq, $(PLATFORM_SDK_VERSION), 31),)
LOCAL_USES_LIBRARIES := com.android.location.provider
LOCAL_OPTIONAL_USES_LIBRARIES := org.apache.http.legacy androidx.window.extensions androidx.window.sidecar
endif
```
We need a similar change in `FakeStore/Android.mk`
```
ifneq ($(call math_gt_or_eq, $(PLATFORM_SDK_VERSION), 31),)
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar
endif
```

**Comment by petefoth** [comment]
Re-opening until the fix is tested

**Comment by kaduvert** [comment]
idk if related but updating to microG 0.3.6 on the latest lineage4microg build from november makes the following self checks false:

 - System spoofs signature
 - GmsCore has correct signature
 - Phonesky has correct signature

<details>
<summary>screen</summary>

![screen.png](https://github.com/user-attachments/assets/eb8bc8c8-6b7d-492f-99b2-169073dca278)
</details>

**Comment by petefoth** [comment]
> updating to microG 0.3.6 on the latest lineage4microg build from november makes the following self checks false:

Which build on which device?

**Comment by kaduvert** [comment]
> > updating to microG 0.3.6 on the latest lineage4microg build from november makes the following self checks false:
> 
> Which build on which device?

lineage-21.0-20241125-microG-sargo

**Comment by petefoth** [comment]
> > Which build on which device?
> 
> lineage-21.0-20241125-microG-sargo

Then a new build should be along in the next day or so, but pleas note what was said in [this XDA forum post](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89871383)
> We are now splitting our builds between two servers, but it seems there are some problems with new builds not booting after an update. This may be caused by differences in the signing keys between the two devices. Whatever the cause, until we have got to the bottom if it and made any required fixes we ***strongly*** recommend backing up your user-installed apps and data ***before*** installing any update, either via OTA or manually

**Comment by ale5000-git** [comment]
The new version of microG no longer use backends so maybe it is time to remove them (for example NominatimGeocoderBackend).

**Comment by petefoth** [comment]
New builds are completing with now obvious problems

Closing
