### ISSUE TITLE
Failing builds for 19.0 due to uses-libraries changes

### ISSUE THREAD

**Issue by poshul** [lineageos4microg/android_vendor_partner_gms#7]
Building 19.0 including GmsCore returns an error:
`FAILED: out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py       --enforce-uses-libraries        --enforce-uses-libraries-status out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status      --aapt out/host/linux-x86/bin/aapt                                  prebuilts/prebuiltapks/GmsCore/com.google.android.gms-212658044.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: [com.android.location.provider]
        - optional libraries in build system: []
                         vs. in the manifest: []
        - tags in the manifest (prebuilts/prebuiltapks/GmsCore/com.google.android.gms-212658044.apk):
                uses-library:'com.android.location.provider'
note: the following options are available:
        - to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
        - to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
        - to fix the check, make build system properties coherent with the manifest
        - see build/make/Changes.md for details`

This is due to enforcing consistency between build-system and manifest in Android 12 (https://source.android.com/devices/tech/dalvik/art-class-loader-context)

**Comment by bananer** [comment]
I did not see this error when building 19.0. Which device are you building for?

**Comment by poshul** [comment]
This was for the FairPhone4.

**Comment by bananer** [comment]
Could you try building again with this repo's branch `lineage-19.0` included and verify that your issue is fixed?

**Comment by petefoth** [comment]
This was fixed a while back LOS 19 builds worked fine LOS stopped supporting that version

Closing
